#!/bin/sh

mkdir -p opk
cp ./roq.elf opk/roq.elf
cp ./icon.png opk/icon.png
cp ./LICENSE.KOS opk/COPYING

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=RoQPlayer
Comment=RoQ video player
Exec=roq.elf %f
Icon=icon
Terminal=false
Type=Application
Categories=applications;
X-OD-NeedsDownscaling=false' > opk/default."$1".desktop

mksquashfs ./opk roq_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
